module.exports = {
    "RECIPE_EN_US" : {
        "agile": "Agile means the ability to create and respond to change in order to succeed in an uncertain and turbulent environment.  Agile Software Development is an umbrella term for a set of methods and practices.  Solutions evolve through collaboration between self-organizing, cross-functional teams utilizing an incremental development strategy.",
        "time box": "A time box is a Fixed increment of time, rather than scope, for a given activity.",
        "sprint": "A Sprint is a Time-boxed iteration of working time, usually 2 to 4 weeks.",
        "sprint planning": "Sprint planning is a Meeting to negotiate the scope for next Sprint where the team pulls in work from the product Owner’s prioritized backlog.",
        "product backlog": "A product backlog means that a product owner creates a wish-list of every feature desired in the product and then prioritize the features.",
        "epic": "Agile methodology says a user story must be independent of other user stories. In a broad sense, there should not be dependency on whether the other stories are implemented or not. But, many times, real world scenario differs. There can be a scenario involving several dependent features and so the concept of epic stories was brought. An epic story can be defined as a large undefined user story that needs to be broken down in smaller pieces before it can be used.",
        "scrum master": "A scrum master is one the most important role (along with product owner) in a scrum based approach. Scrum master is responsible for daily standup meetings and tracking the overall progress. It is the duty of scrum master to make sure the team is not blocked at any point of time due to external or internal issues.",
        "user story": "A user story- simply put, is a way to define a software feature from an end-user perspective. For example, a user story may look like this...As a user, I want to be able to update my profile with age, present occupation and social interests, so that people visiting my profile page get an idea of my interests.",
        "story point": "A story point is an abstract estimation unit of relative size, complexity, and effort to deliver a defined piece of intent to be delivered. Simple intent might be ranked as 1 story point and a very complex task might be ranked 13 story points. This does not mean that the complex task is 13 times more complex than the simple task, it just means that the story is in a more complex category.",
        "stand up": "Each day at the same time, the team meets for 10 to 15minutes to bring everyone up to date. Each team members briefly describes any completed contributions and any obstacles that stand in their way.",
        "sprint team": "A sprint team is a small group, typically 5-6 people, assigned to the same project or effort. Often a business unit will have their own dedicated team. For example, Marketing has 2 dedicated teams while H R has 1 team.",
        "minimum viable product": "A Minimum Viable Product allows you to test an idea by exposing an early version of your product to the target users and customers, to collect relevant data, and to learn from it."
    }
};
